Traceback (most recent call last):
  File "/home/casimir/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/casimir/.local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
(D_M_xy_1.eigenvalues()[2]+D_M_xy_1.eigenvalues()[3]).expand()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/usr/lib/python3/dist-packages/sage/all_cmdline.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;34m([0m[0mD_M_xy_1[0m[0;34m.[0m[0meigenvalues[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0mInteger[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m][0m[0;34m+[0m[0mD_M_xy_1[0m[0;34m.[0m[0meigenvalues[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0mInteger[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mexpand[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'D_M_xy_1' is not defined
NameError: name 'D_M_xy_1' is not defined

