Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Freq√º√®ncies de Gamma a M (i les guardem com un dataframe). Calculem 200 punts en este interval
freq_planol_Gamma_a_M4ts=real_part(sqrt(numpy.linalg.eigvals(\
     numpy.array([D4ts_xy.subs(Solucionspla4ts, a=1, q_x=x*pi, q_y=x*pi/sqrt(3),\
                    M_B=B.mass, M_N=N.mass).numpy(dtype='complex64') for x in arange(0,1,1./200)]))))

DF_freq_planol_Gamma_a_M4ts=pd.DataFrame(freq_planol_Gamma_a_M4ts)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/usr/lib/python3/dist-packages/sage/all_cmdline.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#Freq√º√®ncies de Gamma a M (i les guardem com un dataframe). Calculem 200 punts en este interval[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m freq_planol_Gamma_a_M4ts=real_part(sqrt(numpy.linalg.eigvals(\
[0m[1;32m      3[0m      numpy.array([D4ts_xy.subs(Solucionspla4ts, a=Integer(1), q_x=x*pi, q_y=x*pi/sqrt(Integer(3)),\
[1;32m      4[0m                     M_B=B.mass, M_N=N.mass).numpy(dtype='complex64') for x in arange(Integer(0),Integer(1),RealNumber('1.')/Integer(200))]))))
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'numpy' is not defined
NameError: name 'numpy' is not defined

